FROM ubuntu:latest
LABEL authors="samir"

# Install Node.js and npm
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package* .

RUN npm install

COPY . .

RUN npm run dev

EXPOSE 3000